# Generated by Django 2.2.9 on 2020-02-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=40)),
                ('photo', models.ImageField(null=True, upload_to='products')),
                ('stock', models.IntegerField(null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
