# Generated by Django 2.2.9 on 2020-02-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200205_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_image', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertise')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
