# Generated by Django 2.2.9 on 2020-02-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200207_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
