# Generated by Django 2.2.9 on 2020-02-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200207_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='type_advertise',
            field=models.IntegerField(null=True),
        ),
    ]
