# Generated by Django 2.2.9 on 2020-02-07 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200207_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertise',
            name='description',
        ),
        migrations.RemoveField(
            model_name='advertise',
            name='image',
        ),
        migrations.RemoveField(
            model_name='advertise',
            name='type_advertise',
        ),
    ]
