# Generated by Django 2.2.9 on 2020-02-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200207_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advertise'),
        ),
        migrations.AddField(
            model_name='advertise',
            name='typea',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
