# Generated by Django 2.2.9 on 2020-02-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200207_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Promoción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotion')),
            ],
        ),
    ]
