# Generated by Django 2.2.9 on 2020-02-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_auto_20200211_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
