# Generated by Django 2.2.9 on 2020-02-11 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_auto_20200211_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
    ]
