# Generated by Django 2.2.9 on 2020-02-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0006_auto_20200211_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='game')),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name': 'Maquina', 'verbose_name_plural': 'Maquinas'},
        ),
    ]
