# Generated by Django 2.2.9 on 2020-01-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('dni', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('money', models.FloatField()),
                ('register', models.DateField()),
            ],
        ),
    ]
