# Generated by Django 2.2.9 on 2020-02-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200201_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
    ]
