# Generated by Django 2.2.9 on 2020-02-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
